language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t tjoseph/docker-react -f Deockerfile.dev .

script:
  - docker run -e CI=true tjoseph/docker-react cpm run test